"""Contract Risk Analyzer skill for enterprise agreement auditing and redline synthesis."""
from __future__ import annotations

import logging
import uuid
from typing import Any, Dict, List, Optional

from app.services.llm_client import LLMClient
from app.skills.skill_registry import Skill

logger = logging.getLogger(__name__)


class ContractRiskAnalyzerSkill(Skill):
    """Deep clause-level risk assessment on commercial contracts against standard playbooks."""

    SYSTEM_PROMPT = """You are a senior commercial contracts counsel and enterprise risk assessment specialist.
Analyze the provided contract or legal excerpt across standard commercial clause categories:
- Indemnification (Direct/Third-party/IP scope, mutuality, carve-outs)
- Limitation of Liability (Cap amount, mutual vs unilateral, uncapped exclusions)
- Termination (For cause vs convenience, notice/cure periods, data deletion)
- IP Ownership & Work-for-Hire (Foreground vs Background IP, license grant breadth)
- Confidentiality & Data Protection (DPA timeline, breach notice, survival period)
- Warranties & Disclaimers (AS IS disclaimers, fitness for purpose)
- Auto-renewal / Non-compete / Governing Law

Output Format:
# Contract Risk Report

## Executive Summary
(2-3 sentences summarizing overall risk posture, top 2-3 highest severity items, and role perspective)

## Risk Scorecard
| # | Clause Category | Severity (Critical/High/Medium/Low) | Exposure Summary |

## Detailed Clause Findings & Redline Guidance
For each material finding:
- **Location / Paraphrase**: Summarize key clause obligations (do not copy verbatim).
- **Risk Assessment**: Explain the specific financial or operational exposure.
- **Recommended Redline Direction**: Propose concrete negotiation language adjustments.

## Missing / Silent Clauses
Flag any expected standard protections that are absent from the text.

## Disclaimer
> This report is an automated risk-flagging aid generated by Lumina and does not constitute legal advice. Consult qualified legal counsel before making decisions based on this report."""

    def __init__(self, llm_client: Optional[LLMClient] = None) -> None:
        self.llm = llm_client or LLMClient(task="generator")

    @property
    def name(self) -> str:
        return "contract_risk"

    @property
    def description(self) -> str:
        return "Performs clause-level risk analysis, missing clause detection, and redline guidance on commercial contracts."

    @property
    def category(self) -> str:
        return "legal-compliance"

    @property
    def tags(self) -> List[str]:
        return [
            "contract",
            "legal",
            "risk",
            "redline",
            "clause",
            "compliance",
            "liability",
            "indemnity",
            "msa",
            "nda",
            "sow",
            "agreement",
        ]

    @property
    def parameters_schema(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "contract_text": {"type": "string", "description": "Text of the contract or clause to analyze"},
                "counterparty_role": {"type": "string", "enum": ["customer", "vendor", "unknown"], "default": "unknown"},
                "risk_appetite": {"type": "string", "enum": ["conservative", "standard", "aggressive"], "default": "standard"},
            },
            "required": ["contract_text"],
        }

    def can_handle(self, state: dict) -> bool:
        route = state.get("route", "")
        return route in ("contract_risk", "contract-risk-analyzer")

    def execute(self, state: dict) -> dict:
        query = state.get("query", "")
        thinking_emitter = state.get("thinking_emitter")

        if thinking_emitter:
            thinking_emitter("skill_executor", "Performing deep clause segmentation & legal risk analysis...")

        try:
            response = self.llm.generate_text([
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze contract/clauses in relation to: {query}"},
            ], max_tokens=1600, temperature=0.1)

            analysis_text = response.content.strip()
            chunk_id = f"legal_risk_{uuid.uuid4().hex[:8]}"

            doc = {
                "chunk_id": chunk_id,
                "id": chunk_id,
                "modality": "text",
                "text_repr": f"### Contract Risk Assessment:\n\n{analysis_text}",
                "title": "Contract Risk Analysis Report",
                "score": 1.0,
                "relevance_score": 1.0,
                "rerank_score": 1.0,
                "source": "contract_risk_analyzer",
            }

            state["retrieved_docs"] = [doc]
            state["relevant_docs"] = [doc]
            state["source_docs"] = [doc]
            state["is_sufficient"] = True

            if thinking_emitter:
                thinking_emitter("skill_executor", "Contract risk assessment completed with redline recommendations.")

        except Exception as exc:
            logger.warning("ContractRiskAnalyzerSkill execution failed: %s", exc)

        return state


__all__ = ["ContractRiskAnalyzerSkill"]
